---
config:
  layout: dagre
---
flowchart TB
 subgraph rg["Retained Graph"]
        n1["Graph"]
  end
 subgraph s1["Processor (Audio Thread)"]
        n11["Input Rx"]
        n12["Output Tx"]
        rg
  end
    n7["On native systems, the processor runs a continous loop in a dedicated thread (ideally using some sort of crossthread signal to wait for when more data is needed). The DSP thread runs thes graph at a fixed sample rate/block size (configured by user), and resamples input/output as needed in the loop. On web, this dedicated audio thread loop is handled automatically by the AudioWorklet. All the Processor in the worklet has to worry about is copying input data in and copying output data out to the Graph, and handling high-level data/graph interactions."] --- s1
    n11 --> rg
    s1 -- Events, Node State for Rendering --> n13["Controller (Main Thread)"]
    n13 -- Graph JSON, Control Values, Audio Channel Ports, External/Plugin Binaries --> s1
    rg --> n12
    n13 -- Events, Node State for Rendering, --> n14["GUI (Optional) / Library Code (Optional)"]
    n14 -- Emitted Graph JSON, Graph/Node Configuration, Events, Input/Output Configuration --> n13

    n1@{ shape: rect}
    n11@{ shape: rect}
    n7@{ shape: text}
    n13@{ shape: rect}
    n14@{ shape: rect}
    linkStyle 0 stroke:#BBDEFB,fill:none
