[package]
name = "resonix-graph"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# enables the ability to create WebAssembly-based audio nodes
wasm = ["dep:wasmer"]

# native-env-specific dependencies--enables wasmer default engine configuration
sys = ["wasmer/default"]

# JS-env-specific dependencies (browser, node, deno, etc.)
# TODO: may be able to get a slimmer build by disabling the js default feautures
js = [
	"dep:wasm-bindgen",
	"dep:serde",
	"dep:serde-wasm-bindgen",
	"wasmer/js-default",
]

[dependencies]
hashbrown = "0.15.3"
nohash-hasher = "0.2.0"
petgraph = "0.8.1"
bon = "3.9.1"
thiserror.workspace = true

# optional dependencies
wasmer = { version = "7.1.0", default-features = false, optional = true }
wasm-bindgen = { workspace = true, optional = true }
serde-wasm-bindgen = { version = "0.6.5", optional = true }
serde = { version = "1.0.228", optional = true }

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }
approx = "0.5.1"

[[bench]]
name = "graph"
harness = false
