[package]
name = "resonix-graph"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
wasm = ["dep:wasm-bindgen"]

[dependencies]
hashbrown = "0.15.3"
nohash-hasher = "0.2.0"
petgraph = "0.8.1"
bon = "3.9.1"
thiserror.workspace = true
wasm-bindgen = { workspace = true, optional = true }

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }
approx = "0.5.1"

[[bench]]
name = "graph"
harness = false
