[package]
name = "resonix-audio"
version = "0.1.0"
edition = "2024"

[features]
cpal = ["dep:cpal"]
mock = []

# default channel runtime for now
# ringbuf = ["dep:ringbuf"]

[dependencies]
ringbuf = { version = "0.4.8" }
thiserror.workspace = true
# TODO: is this needed?
cpal = { version = "0.15.3", optional = true }
