[package]
name = "resonix-web"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = { version = "0.2.100" }
js-sys = { version = "0.3.77" }
web-sys = { version = "0.3.77", features = [] }
resonix-graph = { path = "../resonix-graph/" }

[dev-dependencies]
wasm-bindgen = { workspace = true }
wasm-bindgen-test = { workspace = true }
