[package]
name = "resonix"
version = "0.1.0"
edition = "2021"
authors = ["Austin Theriot"]
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.8.4", features = ["small_rng"]}
nohash-hasher = "0.2.0"
log = "0.4"
thiserror = "1.0.40"

# WASM-ONLY dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
# only need wasm-bindgen when compiling for wasm32
cpal = { version = "0.13.5", features = ["wasm-bindgen"], optional = true }
# enabling "js" tells `getrandom` that `rand` should compile with wasm/js features enabled
getrandom = { version = "0.2.6", features = ["js"] }

# NATIVE-ONLY dependencies
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cpal = { version = "0.13.5", optional = true }
getrandom = { version = "0.2.6" }
wasm-logger = "0.2.0"

[dev-dependencies]
cargo-husky = "1"
# async runtime only needed while testing
tokio = { version = "1.28.1", features = ["full"] }
resonix_test_utils = { path = "../resonix_test_utils"}

[features]
# only need cpal when using audio-out (DAC) features
cpal = ["dep:cpal"]


