[package]
name = "resonix-wasm-audio-node"
version = "0.1.0"
edition = "2024"


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
resonix-core = { path = "../resonix-core" }
dlmalloc = { version = "0.2.13", features = ["global"] }
spin = { version = "0.10.0", features = ["once", "mutex"] }
resonix-wasm-audio-node-macros = { path = "../resonix-wasm-audio-node-macros/" }
