name: CI

on:
  push:
    branches:
      - master

jobs:

  build-and-test-workspace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Linux audio library deps
        run: |
          sudo apt-get install -y libasound2-dev

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install stable          

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version          

      - name: Test
        run: |
          cargo check --workspace
          cargo test --workspace

  build-demos-granular-synthesizer-web:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: demos/granular_synthesizer_web

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version-file: 'demos/granular_synthesizer_web/.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build