name: Test

on:
  push:
    branches:
      - master
      # TODO: remove this once v2 is merged to master
      - v2
  pull_request:

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update apt
        run: sudo apt update
      - name: Install alsa
        run: sudo apt-get install libasound2-dev
      - name: Install libjack
        run: sudo apt-get install libjack-jackd2-dev libjack-jackd2-0
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: Run without features
        run: cargo test --all --no-default-features --verbose
      - name: Run all features
        run: cargo test --all --all-features --verbose

  chrome-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      # only test resonix-web for now, since web bindings are only present there
      - run: wasm-pack test --chrome --headless crates/resonix-web

  wasm-build:
    # this only confirms that the Rust source builds for wasm-unknown-unknown
    # It does not test the javascript/web integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install stable (wasm32 target)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - name: Cargo Build
        working-directory: ./examples/wasm-beep
        run: cargo build --workspace --target wasm32-unknown-unknown

  miri:
    name: miri
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: miri

      - name: Setup miri
        run: cargo miri setup

      - name: Run miri
        run: cargo miri test --all-features
