name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        toolchain:
          - nightly
        cargo_flags:
          - "--no-default-features"
          - "--all-features"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all ${{ matrix.cargo_flags }}

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all ${{ matrix.cargo_flags }}

  miri:
    name: miri
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: miri

      - name: Setup miri
        run: cargo miri setup

      - name: Run miri
        run: cargo miri test --all-features
