name: Test

on:
  push:
    branches:
      - master
      # TODO: remove this once v2 is merged to master
      - v2
      - v2-*
  pull_request:

jobs:
  clippy-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Update apt
        run: sudo apt update
      - name: Install alsa
        run: sudo apt-get install libasound2-dev
      - name: Install libjack
        run: sudo apt-get install libjack-jackd2-dev libjack-jackd2-0
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
          target: armv7-linux-androideabi
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  rustfmt-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Run rustfmt
        run: cargo fmt --all -- --check

  ubuntu-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Update apt
        run: sudo apt update
      - name: Install alsa
        run: sudo apt-get install libasound2-dev
      - name: Install libjack
        run: sudo apt-get install libjack-jackd2-dev libjack-jackd2-0
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: Run without features
        run: cargo test --all --no-default-features --verbose
      - name: Run all features
        run: cargo test --all --all-features --verbose

  windows-test:
    strategy:
      matrix:
        version: [x86_64, i686]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install ASIO SDK
        env:
          LINK: https://www.steinberg.net/asiosdk
        run: |
          curl -L -o asio.zip $env:LINK
          7z x -oasio asio.zip
          move asio\*\* asio\
      - name: Install ASIO4ALL
        run: choco install asio4all
      - name: Install llvm and clang
        run: choco install llvm
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.version }}-pc-windows-msvc
      - name: Run without features
        run: cargo test --all --no-default-features --verbose
      - name: Run all features
        run: |
          $Env:CPAL_ASIO_DIR = "$Env:GITHUB_WORKSPACE\asio"
          cargo test --all --all-features --verbose

  macos-test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install llvm and clang
        run: brew install llvm
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: Run without features
        run: cargo test --all --no-default-features --verbose
      - name: Run all features
        run: cargo test --all --all-features --verbose

  chrome-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      # only test resonix-web for now, since web bindings are only present there
      - run: wasm-pack test --chrome --headless crates/resonix-web

  wasm-build:
    # this only confirms that the Rust source builds for wasm-unknown-unknown
    # It does not test the javascript/web integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install stable (wasm32 target)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - name: Cargo Build
        run: cargo build --workspace --target wasm32-unknown-unknown

  miri:
    name: miri
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
      - name: Update apt
        run: sudo apt update
      - name: Install alsa
        run: sudo apt-get install libasound2-dev
      - name: Install libjack
        run: sudo apt-get install libjack-jackd2-dev libjack-jackd2-0
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: miri

      - name: Setup miri
        run: cargo miri setup

      - name: Run miri
        # many-seeds helps eliminate the chance of incidental, uncaught UB
        run: MIRIFLAGS="-Zmiri-many-seeds=0..16" cargo miri test --all-features
