name: Tests

on:
  push:
  pull_request:
  # run 4 times a month at 6:40 UTC
  schedule: [cron: "40 6 1,8,15,22 * *"]

jobs:

  build-and-test-workspace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install cargo-hack
        uses: taiki-e/install-action@cargo-hack

      - name: Install Linux audio library deps
        run: |
          sudo apt-get install -y libasound2-dev

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install stable          

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version          

      - name: Test
        run: |
          cargo hack check --workspace --feature-powerset
          cargo hack test --workspace --feature-powerset -- --skip dac_tests_on_hardware

      - name: Check compilation with and without DAC
        working-directory: crates/resonix
        run: |
          cargo check
          cargo check --features dac